# scripts/crea_insegnamenti_LMfis.py

from dispense.models import Corso, Insegnamento

# recupero il riferimento al CdL LM-Fisica
LMfis = Corso.objects.get(titolo="LM-Fisica")
	
# creo gli insegnamenti del CdL fisica magistrale
insegnamento = Insegnamento(titolo="Chimica fisica delle biomolecole", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Elettronica e acquisizione dati", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fabbricazione e caratterizzazione di nanostrutture", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fisica dei semiconduttori", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fisica dei sistemi biologi", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fisica della materia condensata I", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fisica della materia condensata II", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fisica delle transizioni di fase", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fisica teorica applicata", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fondamenti di nanoscienze", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Istituzioni di fisica teorica", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Laboratorio di fisica moderna", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Meccanica quantistica moderna", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Meccanica statistica e processi stocastici", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Scoperte scientifiche e societa'", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Sensori ed attuatori", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Teoria classica dei campi e relativita'", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Teoria quantisitica dei campi", corso=LMfis)
insegnamento.save()
insegnamento = Insegnamento(titolo="Teoria quantistica dei sistemi a molti corpi", corso=LMfis)
insegnamento.save()

