# scripts/crea_insegnamenti_LTmate.py

from dispense.models import Corso, Insegnamento

# recupero il riferimento al CdL LT-Matematica
LTmate = Corso.objects.get(titolo="LT-Matematica")
	
# creo gli insegnamenti del CdL matematica triennale
insegnamento = Insegnamento(titolo="Algebra A", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Algebra B", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Algebra lineare", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Algoritmi e strutture dati", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Analisi matematica I", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Analisi matematica II", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Analisi matematica A", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Analisi numerica A", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Calcolo numerico", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Catene di Markov", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fisica A", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fisica B", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fisica matematica A", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fisica matematica B", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fondamenti di matematica I", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Geometria", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Geometria B", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Geometria delle curve", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Informatica di base e applicazioni scientifiche", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Informatica generale", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Laboratorio di fisica I", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Linguaggi formali e compilazione", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Inglese", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Ottimizzazione numerica", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Probabilita' e statistica", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Programmazione II", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Teoria della misura", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Termodinamica e fluidi", corso=LTmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Topologia algebrica", corso=LTmate)
insegnamento.save()
