# scripts/crea_insegnamenti_LMmate.py

from dispense.models import Corso, Insegnamento

# recupero il riferimento al CdL LM-Matematica
LMmate = Corso.objects.get(titolo="LM-Matematica")
	
# creo gli insegnamenti del CdL matematica magistrale
insegnamento = Insegnamento(titolo="Algebra e teoria dei codici", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Algoritmi di approssimazione", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Analisi superiore", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Calcolo delle variazioni", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Calcolo parallelo", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Didattica della matematica", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Equazioni alle derivate parziali", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Fondamenti di matematica II", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Geometria combinatoria", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Laboratorio di fisica computazionale", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Matematiche elementari da un punto di vista superiore", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Meccanica statistica e sistemi dinamici", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Metodi matematici della meccanica quantistica", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Metodi numerici", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Metodi probabilistici", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Processi stocastici", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Sistemi complessi", corso=LMmate)
insegnamento.save()
insegnamento = Insegnamento(titolo="Strutture algebriche", corso=LMmate)
insegnamento.save()
